# Generated by Django 5.2.4 on 2025-07-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('price_per_night', models.PositiveIntegerField(help_text='Price per night in AUD', verbose_name='Price')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('pets_allowed', models.BooleanField(default=True, help_text='Is pets allowed?', verbose_name='Pets Allowed?')),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
            ],
        ),
    ]
